export const GET_ITEMS = 'GET_ITEMS';
export const ADD_ITEM = 'ADD_ITEM';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const ITEMS_LOADING = 'ITEMS_LOADING ';





export const GET_CATEGORIES = 'GET_CATEGORIES';
export const ADD_CATEGORIE = 'ADD_CATEGORIE';
export const REMOVE_CATEGORIE = 'REMOVE_CATEGORIE';
export const GET_ONE_CATEGORIES ='GET_ONE_CATEGORIES';
export const CATEGORIES_LOADING = 'CATEGORIES_LOADING ';
